### ISSUE TITLE
Parsing ink file?

### ISSUE THREAD

**Issue by fireton** [premek/pink#1]
As far as I understand you are parsing the ink source? Why not compiled JSON?
I was thinking to implement lua version of the ink runtime myself but my idea was to run the compiled form since it consist of "low level" commands and not depends that much of a new features that developers would add to ink "high level" language.

**Comment by premek** [comment]
Hi, your approach may be better and I thought about it too, but this is why i decided to parse the ink file and not to use the JSON:
- I was not able to make the official parser / editor running on linux (it should be possible, the official distribution uses wine)
- I wanted to learn PEG parsing :)

I do not aim to make my parser 100% compatible with the official one. Currently it supports just the very basics but it is already possible to use it for a very simple game.

**Comment by premek** [comment]
Also, the ink file may be more stable than the json and parsing it would allow me to parse some things a bit differently. For example I can allow some things that would be an error in the original ink parser if I want.
